version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "wiki-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-k33lepwtbzvt"
s3_prefix = "wiki-stack"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
